import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Star, Download, Clock, Tag, ShieldCheck, ChevronRight, Sparkles, Terminal, FileCode, CheckCircle2, User, Share2 } from 'lucide-react';
import LoadingSpinner from '../components/ui/LoadingSpinner';
import MinoShieldBadge from '../components/security/MinoShieldBadge';
import { getPluginById } from '../services/api';

const SAMPLE_PLUGINS_DATABASE = {
  'p-mine-1': {
    id: 'p-mine-1',
    title: 'Ultimate Economy & Vault System',
    authorName: 'MinoDeveloper',
    gameName: 'Minecraft',
    price: '14.99',
    rating: '4.9',
    reviewsCount: 142,
    downloads: 4820,
    version: 'v2.4.0',
    lastUpdated: '2 days ago',
    category: 'Economy & Vault',
    coverImageUrl: '/images/categories/minecraft.png',
    summary: 'High-performance multi-currency vault system with GUI ATMs, pin codes, and transaction logs.',
    overview: `
      <h3>Overview</h3>
      <p>The premier economy plugin for modern Minecraft servers. Built from the ground up for Paper, Purpur, and Folia with zero lag and instant SQL synchronization.</p>
      <br/>
      <h4>Key Features</h4>
      <ul>
        <li>Multi-Currency Support (Coins, Gems, Bank Credits)</li>
        <li>Interactive GUI ATM & Banking System with PIN codes</li>
        <li>Automated Interest & Loan Management</li>
        <li>Full Vault, PlaceholderAPI, and Discord Webhook integration</li>
      </ul>
    `,
    installation: `
      <ol>
        <li>Download the <code>.jar</code> file using the download button on this page.</li>
        <li>Place the file into your server's <code>/plugins</code> directory.</li>
        <li>Restart your server to generate the default configuration.</li>
        <li>Configure your database in <code>plugins/Economy/config.yml</code>.</li>
      </ol>
    `,
    commands: `
      <ul>
        <li><code>/balance [player]</code> - View your or another player's balance (<code>mino.eco.balance</code>)</li>
        <li><code>/pay &lt;player&gt; &lt;amount&gt;</code> - Send coins to another player (<code>mino.eco.pay</code>)</li>
        <li><code>/bank open</code> - Open personal banking GUI (<code>mino.bank.use</code>)</li>
        <li><code>/eco give/take/set &lt;player&gt; &lt;amount&gt;</code> - Admin balance control (<code>mino.eco.admin</code>)</li>
      </ul>
    `,
    configSample: `# Ultimate Economy Configuration
# Generated by MinoForge

database:
  type: "SQLITE" # Options: SQLITE, MYSQL, POSTGRESQL
  host: "localhost"
  port: 3306
  database: "minecraft_eco"
  username: "root"
  password: "password123"

currency:
  name-singular: "Coin"
  name-plural: "Coins"
  symbol: "$"
  starting-balance: 500.00
  allow-negative-balance: false

banking:
  enabled: true
  max-accounts-per-player: 3
  daily-interest-rate: 0.02 # 2% daily interest
`
  },
  'p-fivem-2': {
    id: 'p-fivem-2',
    title: 'Advanced Fuel & Electric Charging System',
    authorName: 'FiveMDev_99',
    gameName: 'FiveM',
    price: '9.99',
    rating: '4.8',
    reviewsCount: 88,
    downloads: 2150,
    version: 'v1.1.2',
    lastUpdated: '1 week ago',
    category: 'Vehicles & Mechanics',
    coverImageUrl: '/images/categories/fivem.png',
    summary: 'Realistic gas stations, EV charging stations, Jerry cans, and smooth 60fps UI for QBCore and ESX.',
    overview: `
      <h3>Overview</h3>
      <p>A next-generation vehicle refueling system for FiveM. Features animated nozzle physics, fuel consumption based on RPM/speed, EV chargers for electric cars, and Jerry cans with roadside delivery.</p>
      <br/>
      <h4>Key Features</h4>
      <ul>
        <li>Optimized 0.00ms idle resmon performance</li>
        <li>Supports both QBCore, ESX Legacy, and standalone frameworks</li>
        <li>Jerry can refueling and roadside mechanics</li>
        <li>Electric vehicle charging stations with sound effects</li>
        <li>Sleek modern NUI interface with customizable colors</li>
      </ul>
    `,
    installation: `
      <ol>
        <li>Extract <code>advanced_fuel</code> into your <code>resources/[standalone]</code> directory.</li>
        <li>Ensure you have <code>ox_lib</code> and <code>ox_target</code> or <code>qb-target</code> installed.</li>
        <li>Add <code>ensure advanced_fuel</code> in your <code>server.cfg</code>.</li>
        <li>Restart your server or start the resource in console.</li>
      </ol>
    `,
    commands: `
      <ul>
        <li><code>/setfuel [amount]</code> - Admin command to modify vehicle fuel percentage</li>
        <li><code>/givejerrycan [player]</code> - Give a fuel jerry can to target player</li>
      </ul>
    `,
    configSample: `-- FiveM Fuel Configuration
-- Format: Lua (QBCore / ESX)

Config = {}
Config.Framework = 'qb' -- 'qb', 'esx', or 'standalone'
Config.Target = 'ox_target' -- 'ox_target' or 'qb-target'
Config.FuelPrice = 1.75 -- Price per Liter

Config.ElectricVehicles = {
    'raiden',
    'neon',
    'cyclone',
    'iwagen',
    'tezeract'
}

Config.JerryCanCapacity = 25.0
Config.RefuelSpeed = 1.5
`
  },
  'p-bot-3': {
    id: 'p-bot-3',
    title: 'Discord Ticket & Transcripts Bot',
    authorName: 'BotCrafter',
    gameName: 'Discord',
    price: '0.00',
    rating: '5.0',
    reviewsCount: 210,
    downloads: 3940,
    version: 'v1.0.0',
    lastUpdated: '3 weeks ago',
    category: 'Community & Moderation',
    coverImageUrl: '/images/categories/discord.png',
    summary: 'Automated ticket buttons, transcript HTML archiving, and staff rating system for Discord servers.',
    overview: `
      <h3>Overview</h3>
      <p>A professional Discord support ticket bot designed for gaming communities. Automatically creates ticket channels with one-click buttons, logs rich HTML transcripts to a staff channel, and asks users for staff ratings upon ticket closure.</p>
      <br/>
      <h4>Key Features</h4>
      <ul>
        <li>Interactive Discord Button & Modal menus</li>
        <li>Self-hosted HTML transcripts viewable in browser</li>
        <li>Staff performance ratings (1 to 5 stars)</li>
        <li>Auto-close idle tickets after 24 hours of inactivity</li>
        <li>Role-based permissions for support staff</li>
      </ul>
    `,
    installation: `
      <ol>
        <li>Extract the bot archive and run <code>npm install</code>.</li>
        <li>Copy your Discord Bot Token into <code>config.json</code>.</li>
        <li>Run <code>npm start</code> or use PM2 for continuous hosting: <code>pm2 start index.js --name ticket-bot</code>.</li>
        <li>Type <code>/ticket setup</code> in your Discord server to deploy the ticket panel.</li>
      </ol>
    `,
    commands: `
      <ul>
        <li><code>/ticket setup</code> - Deploy the interactive ticket panel to a channel</li>
        <li><code>/ticket close [reason]</code> - Close active ticket and export transcript</li>
        <li><code>/ticket add [user]</code> - Add user to current ticket</li>
      </ul>
    `,
    configSample: `// Discord Ticket Bot Configuration
// Format: JSON

{
  "botToken": "YOUR_DISCORD_BOT_TOKEN",
  "clientId": "123456789012345678",
  "guildId": "987654321098765432",
  "ticketCategoryChannelId": "112233445566778899",
  "transcriptLogsChannelId": "998877665544332211",
  "supportStaffRoleId": "554433221100998877",
  "maxOpenTicketsPerUser": 2,
  "askFeedbackOnClose": true
}
`
  }
};

const PluginDetailPage = () => {
  const { id } = useParams();
  const [loading, setLoading] = useState(true);
  const [plugin, setPlugin] = useState(null);
  const [activeTab, setActiveTab] = useState('overview');

  useEffect(() => {
    setLoading(true);
    getPluginById(id)
      .then(res => {
        setPlugin(res.data);
      })
      .catch(() => {
        // Match specific plugin ID from database or fallback to first
        const found = SAMPLE_PLUGINS_DATABASE[id] || SAMPLE_PLUGINS_DATABASE['p-mine-1'];
        setPlugin(found);
      })
      .finally(() => {
        setLoading(false);
      });
  }, [id]);

  if (loading) return <LoadingSpinner />;
  if (!plugin) return <div className="text-center py-20 text-xl text-slate-400">Plugin not found</div>;

  const isFree = parseFloat(plugin.price) === 0 || plugin.price === '0.00' || plugin.price === 'Free';

  return (
    <div className="bg-[#0b0f19] min-h-screen text-white py-10 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        
        {/* Breadcrumb */}
        <div className="flex items-center gap-2 text-xs text-slate-400 mb-8">
          <Link to="/" className="hover:text-blue-400">Home</Link>
          <ChevronRight className="w-3.5 h-3.5" />
          <Link to="/plugins" className="hover:text-blue-400">Marketplace</Link>
          <ChevronRight className="w-3.5 h-3.5" />
          <span className="text-white font-medium truncate">{plugin.title}</span>
        </div>

        <div className="flex flex-col lg:flex-row gap-8 items-start">
          
          {/* Main Column */}
          <div className="flex-1 w-full space-y-8">
            
            {/* Header Showcase Card */}
            <div className="bg-slate-900/80 backdrop-blur-xl rounded-3xl border border-white/10 overflow-hidden shadow-2xl">
              <div className="aspect-[21/9] w-full bg-slate-950 relative overflow-hidden">
                <img 
                  src={plugin.coverImageUrl || '/images/categories/minecraft.png'} 
                  alt={plugin.title}
                  className="w-full h-full object-cover filter brightness-85" 
                />
                <div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/40 to-transparent" />
                
                <div className="absolute top-4 right-4">
                  <span className="px-3.5 py-1.5 bg-slate-900/90 backdrop-blur-md rounded-xl text-xs font-extrabold text-blue-400 border border-white/10 shadow-lg">
                    {plugin.gameName || plugin.game}
                  </span>
                </div>
              </div>

              <div className="p-6 md:p-8">
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-4">
                  <div>
                    <h1 className="text-2xl md:text-3xl lg:text-4xl font-black text-white tracking-tight mb-2">
                      {plugin.title}
                    </h1>
                    <p className="text-sm text-slate-400 flex items-center gap-2">
                      Developed by <Link to={`/users/${plugin.authorName}`} className="text-blue-400 font-bold hover:underline">{plugin.authorName}</Link>
                    </p>
                  </div>
                  
                  <div className="flex items-center gap-3">
                    <span className="text-3xl font-black text-emerald-400">
                      {isFree ? 'Free' : `$${plugin.price}`}
                    </span>
                  </div>
                </div>

                {/* Metrics bar */}
                <div className="flex flex-wrap items-center gap-6 pt-6 border-t border-white/5 text-xs text-slate-300">
                  <div className="flex items-center gap-1.5">
                    <Star className="w-4 h-4 text-amber-400 fill-amber-400" />
                    <strong className="text-white text-sm">{plugin.rating}</strong>
                    <span className="text-slate-400">({plugin.reviewsCount} reviews)</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <Download className="w-4 h-4 text-blue-400" />
                    <strong className="text-white text-sm">{plugin.downloads.toLocaleString()}</strong>
                    <span className="text-slate-400">downloads</span>
                  </div>
                  <MinoShieldBadge />
                </div>
              </div>
            </div>

            {/* Multi-Tab Documentation Hub */}
            <div className="bg-slate-900/80 backdrop-blur-xl rounded-3xl border border-white/10 overflow-hidden shadow-2xl p-6 md:p-8">
              
              {/* Tab Navigation */}
              <div className="flex flex-wrap gap-2 pb-6 border-b border-white/10">
                {[
                  { id: 'overview', label: 'Overview' },
                  { id: 'install', label: 'Installation' },
                  { id: 'commands', label: 'Commands & Perms' },
                  { id: 'config', label: 'Sample Config' },
                ].map(tab => (
                  <button
                    key={tab.id}
                    onClick={() => setActiveTab(tab.id)}
                    className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${activeTab === tab.id ? 'bg-blue-600 text-white shadow-md' : 'text-slate-400 hover:text-white hover:bg-slate-800'}`}
                  >
                    {tab.label}
                  </button>
                ))}
              </div>

              {/* Tab Content */}
              <div className="pt-6">
                {activeTab === 'overview' && (
                  <div 
                    className="prose prose-invert max-w-none text-slate-300 text-sm leading-relaxed"
                    dangerouslySetInnerHTML={{ __html: plugin.overview || plugin.summary }}
                  />
                )}

                {activeTab === 'install' && (
                  <div 
                    className="prose prose-invert max-w-none text-slate-300 text-sm leading-relaxed"
                    dangerouslySetInnerHTML={{ __html: plugin.installation || '<p>Follow standard plugin installation for this platform.</p>' }}
                  />
                )}

                {activeTab === 'commands' && (
                  <div 
                    className="prose prose-invert max-w-none text-slate-300 text-sm leading-relaxed"
                    dangerouslySetInnerHTML={{ __html: plugin.commands || '<p>No custom commands required.</p>' }}
                  />
                )}

                {activeTab === 'config' && (
                  <div className="space-y-4">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-bold text-slate-400">Default Configuration</span>
                      <Link
                        to="/ai-config"
                        className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-blue-500/10 hover:bg-blue-500/20 text-blue-400 text-xs font-bold rounded-lg border border-blue-500/30 transition-colors"
                      >
                        <Sparkles className="w-3.5 h-3.5" />
                        <span>Customize with AI</span>
                      </Link>
                    </div>
                    <pre className="p-4 rounded-2xl bg-slate-950 border border-white/10 font-mono text-xs text-blue-200 overflow-x-auto">
                      {plugin.configSample}
                    </pre>
                  </div>
                )}
              </div>
            </div>

          </div>

          {/* Sidebar */}
          <div className="w-full lg:w-80 flex-shrink-0 space-y-6">
            
            {/* Purchase / Download Card */}
            <div className="bg-slate-900/90 backdrop-blur-xl rounded-3xl border border-white/10 p-6 shadow-2xl sticky top-24 space-y-5">
              <button 
                onClick={() => alert(`Starting download for ${plugin.title}...`)}
                className="w-full py-4 px-6 bg-gradient-to-r from-blue-600 to-blue-500 hover:from-blue-500 hover:to-blue-400 text-white font-bold rounded-2xl shadow-xl shadow-blue-600/30 transition-all flex items-center justify-center gap-2 text-base"
              >
                <Download className="w-5 h-5" />
                <span>{isFree ? 'Download Free' : `Buy Now for $${plugin.price}`}</span>
              </button>

              {/* AI Config Banner */}
              <Link
                to="/ai-config"
                className="block p-4 rounded-2xl bg-gradient-to-br from-blue-600/20 to-purple-600/20 border border-blue-500/30 hover:border-blue-400/50 transition-all group"
              >
                <div className="flex items-center gap-2 text-blue-300 font-bold text-xs mb-1">
                  <Sparkles className="w-4 h-4 text-blue-400" />
                  <span>AI Config Generator</span>
                </div>
                <p className="text-[11px] text-slate-300 leading-relaxed">
                  Need a custom rank or economy configuration? Let MinoForge AI write it for you.
                </p>
              </Link>

              {/* Details table */}
              <div className="space-y-3 pt-4 border-t border-white/5 text-xs">
                <div className="flex justify-between">
                  <span className="text-slate-400 flex items-center gap-1.5"><Clock className="w-3.5 h-3.5" /> Updated</span>
                  <strong className="text-white">{plugin.lastUpdated}</strong>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-400 flex items-center gap-1.5"><Tag className="w-3.5 h-3.5" /> Version</span>
                  <strong className="font-mono text-white">{plugin.version}</strong>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-400">Category</span>
                  <strong className="text-blue-400">{plugin.gameName || plugin.game}</strong>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-400">Security</span>
                  <strong className="text-emerald-400 font-bold">MinoShield Verified</strong>
                </div>
              </div>
            </div>

          </div>

        </div>

      </div>
    </div>
  );
};

export default PluginDetailPage;
